#!/bin/bash

# Replace DASK_DASHBOARD_URL with the proxy location
# sed -i -e "s|DASK_DASHBOARD_URL|${JUPYTERHUB_BASE_URL}user/${JUPYTERHUB_USER}/proxy/8787/status|g" binder/jupyterlab-workspace.json


dnf install python3-pyqt6.sip

# Import the workspace
jupyter lab workspaces import binder/jupyterlab-workspace.json

exec "$@"
